solon.app:
  group: demo       #配置服务使用的默认组
  name: helloapp    #发现服务使用的应用名

solon.cloud.nacos:
  server: 172.168.0.48:8848   #nacos服务地址
  username: nacos             #nacos链接账号
  password: nacos             #nacos链接密码
  config:
    loadKey: "test.properties"
