solon.app:
  group: demo       #配置服务使用的默认组
  name: helloapp    #发现服务使用的应用名

solon.cloud.nacos:
  server: 110.43.46.164:8848   #nacos服务地址
  username: nacos             #nacos链接账号
  password: nacos             #nacos链接密码
