solon.app:
  group: demo       #配置服务使用的默认组
  name: helloapp    #发现服务使用的应用名

solon.cloud.water:
  server: water   #water服务地址
  config:
    loadKey: "test.properties"
  discovery:
    enable: true  #设为 false 时，solon.cloud.local 会生效（一般用于本地调试）


solon.cloud.local:
  discovery:
    service:
      helloapi:
        - "http://localhost:7112"
