server.port: 7112
server.http.name: helloapi.http #为http信号，另取个名字；让 solon.app.name 留给 socketd 专用

solon.app:
  group: demo
  name: helloapi    #发现服务使用的应用名（在Demo，将被NimaClient引用）

solon.cloud.consul:
  server: 127.0.0.1   #consul服务地址