solon.app:
  group: demo       #配置服务使用的默认组
  name: helloproducer    #发现服务使用的应用名

solon.cloud.rocketmq:
  server: localhost:5672   #rocketmq服务地址
  username: root           #rocketmq链接账号
  password: 123456         #rocketmq链接密码
